# Generated by Django 4.1.5 on 2023-01-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('series', models.CharField(choices=[('Heian', 'Heian'), ('Tekki', 'Tekki'), ('Bassai', 'Bassai'), ('Kanku', 'Kanku')], max_length=30)),
                ('hiragana', models.CharField(max_length=20)),
                ('kanji', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SE', 'Southeast'), ('SW', 'Southwest')], max_length=2)),
                ('lead_foot', models.CharField(choices=[('R', 'right'), ('L', 'left'), ('N', 'neither')], max_length=1)),
                ('hip', models.CharField(choices=[('S', 'shomen'), ('H', 'hanmi'), ('G', 'gyakuhanmi'), ('N', 'neither')], max_length=1)),
                ('active_side', models.CharField(choices=[('R', 'right'), ('L', 'left'), ('N', 'neither'), ('B', 'both')], max_length=1)),
                ('speed', models.CharField(choices=[('F', 'fast'), ('S', 'slow')], max_length=1)),
                ('snapthrust', models.CharField(choices=[('S', 'snap'), ('T', 'thrust')], max_length=1)),
                ('interm_move', models.BooleanField()),
                ('breath', models.CharField(choices=[('I', 'in'), ('O', 'out'), ('IO', 'in-out'), ('OI', 'out-in')], max_length=2)),
                ('kiai', models.BooleanField()),
                ('kata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kata_moveset.kata')),
            ],
        ),
        migrations.CreateModel(
            name='Stances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('hiragana', models.CharField(max_length=20)),
                ('kanji', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('hiragana', models.CharField(max_length=20)),
                ('kanji', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueToMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('J', 'jodan'), ('C', 'chudan'), ('G', 'gedan'), ('O', 'other')], max_length=1)),
                ('move_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kata_moveset.move')),
                ('technique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kata_moveset.technique')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='stance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kata_moveset.stances'),
        ),
    ]
