# Generated by Django 4.1.5 on 2023-01-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kata_moveset', '0002_stance_alter_technique_description_alter_move_stance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='technique_type',
            field=models.CharField(choices=[('PU', 'punch'), ('B', 'block'), ('K', 'kick'), ('S', 'strike'), ('PR', 'prep'), ('O', 'other')], default='O', max_length=10),
        ),
    ]
