# Generated by Django 4.1.5 on 2023-01-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kata_moveset', '0003_technique_technique_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='stance_initial',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='kata',
            name='series',
            field=models.CharField(choices=[('Heian', 'Heian'), ('Tekki', 'Tekki'), ('Bassai', 'Bassai'), ('Kanku', 'Kanku'), ('Other', 'Other')], max_length=30),
        ),
    ]
