# Generated by Django 4.1.5 on 2023-01-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kata_moveset', '0004_stance_stance_initial_alter_kata_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='technique_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
