# Generated by Django 4.1.5 on 2023-01-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kata_moveset', '0005_alter_technique_technique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stance',
            name='stance_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
