# Generated by Django 4.1.5 on 2023-01-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kata_moveset', '0006_alter_kata_name_alter_stance_stance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='technique',
            field=models.ManyToManyField(through='kata_moveset.TechniqueToMove', to='kata_moveset.technique'),
        ),
    ]
